.obj:
	mkdir -p .obj test/.obj

%.o: %.cc

.obj/%.o: %.cc
	@echo "(CC) $@"
	@$(COMPILE.cc) $(OUTPUT_OPTION) $<

test/.obj/%.o: test/%.cc
	@echo "(CC) $@"
	@$(COMPILE.cc) $(OUTPUT_OPTION) $<

%: .obj/%.o .obj
	@@echo "(LD) $@"
	@$(LD) $(LDLIBS) $(OBJS) -o $@
