.obj:
	mkdir -p .obj test/.obj

%.o: %.cc

.obj/%.o: %.cc .obj
	$(COMPILE.cc) $(OUTPUT_OPTION) $<

test/.obj/%.o: test/%.cc .obj
	$(COMPILE.cc) $(OUTPUT_OPTION) $<

%: .obj/%.o
	$(LD) $^ -lpthread -o $@
