.obj:
	mkdir -p .obj test/.obj

%.o: %.cc

.obj/%.o: %.cc .obj
	@echo "(CC) $@"
	@$(COMPILE.cc) $(OUTPUT_OPTION) $<

test/.obj/%.o: test/%.cc .obj
	@echo "(CC) $@"
	@$(COMPILE.cc) $(OUTPUT_OPTION) $<

%: .obj/%.o
	@@echo "(LD) $@"
	@$(LD) $^ -o $@
